from enum import Enum


class TransactionType(Enum):
    HOME = 'HOME'
    FOOD = 'FOOD'
    SERVICES = 'SERVICES'
    CLOTHING = 'CLOTHING'
    HEALTH = 'HEALTH'
    TRANSPORT = 'TRANSPORT'
    ENTERTAINMENT = 'ENTERTAINMENT'
    MISCELLANEOUS = 'MISCELLANEOUS'
